Logstistic Regrstion

In [9]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [10]:
df = pd.read_csv("../data/MachineLearning/narrative_model_dataset_finalPLS.csv")

In [11]:
X = df.drop(columns=["won"])
y = df["won"]

In [12]:
X.head()

,first_girl,introduction_order,appearance_order,heroine_count,high_heroine_count,introduced_early,has_childhood_connection,is_modern,hair_color_Black,hair_color_Blonde,...,romance_type_Harem,romance_type_Love Triangle,romance_type_Love Triangle/Harem,romance_type_Multiple Romance Candidates,romance_type_Reverse Harem,romance_type_Romance Pairing,romance_type_Romance/Harem,romance_type_Romantic Comedy,romance_type_Romantic Rivalry,romance_type_Single Romance
0,1,1,1,5,1,1,1,1,False,True,...,True,False,False,False,False,False,False,False,False,False
1,0,2,1,5,1,1,1,1,True,False,...,True,False,False,False,False,False,False,False,False,False
2,0,3,2,5,1,1,0,1,False,False,...,True,False,False,False,False,False,False,False,False,False
3,0,4,3,5,1,0,1,1,False,False,...,True,False,False,False,False,False,False,False,False,False
4,0,5,4,5,1,0,0,1,True,False,...,True,False,False,False,False,False,False,False,False,False

In [13]:
y.head()

0    1
1    0
2    0
3    0
4    0
Name: won, dtype: int64

In [14]:
X.shape
y.value_counts()

won
0    314
1     64
Name: count, dtype: int64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state= 42

)

In [19]:
X_train.shape

(302, 71)

In [20]:
X_test.shape

(76, 71)

In [23]:
y_train.value_counts()

won
0    248
1     54
Name: count, dtype: int64

In [24]:
y_test.value_counts()

won
0    66
1    10
Name: count, dtype: int64

In [28]:
LOGmodel = LogisticRegression(
    max_iter=1000
)
LOGmodel.fit(
    X_train,
    y_train
)

LogisticRegression(max_iter=1000)

In [29]:
LOGmodel.coef_

array([[ 2.33528252, -0.87035684, -0.30198387, -0.32149566,  0.33465334,
        -0.71627426, -0.68277329, -0.31129711,  0.1993265 , -0.84393812,
        -0.22952196, -0.46627627,  0.91744452,  0.92201433,  0.10249834,
         0.51659513, -0.33157247, -0.81926927,  0.03445587, -0.03808964,
         0.02360093,  0.00567378,  0.31061021, -0.52797296,  0.01281383,
         0.21512044,  0.52478248, -0.0228598 , -0.05143374, -0.44873234,
         0.16932405, -0.04985816, -0.1177093 ,  0.08592045, -0.38503954,
         0.23558064,  0.21319021, -0.14789517, -0.08284417, -0.09144727,
         0.31784138, -0.11551255, -0.42772831,  0.41120317,  0.72935669,
         0.01705548,  0.1047986 ,  0.07596945,  0.11273113,  0.23821611,
        -0.54367996,  0.16591851, -0.1709388 ,  0.22154843, -0.17246463,
        -0.51909795, -0.53165868, -0.01362028,  0.50180028,  0.15934948,
        -0.38503954, -0.23062722,  0.12218654, -0.2983903 , -0.24211747,
         0.05782065,  0.2970036 ,  0.29672101, -0.26218852,  0.14019837,
         0.12114993]])

In [30]:
importance = pd.DataFrame({
    "feature": X_train.columns,
    "weight": LOGmodel.coef_[0]
})

In [ ]:
# Biggest winner predictors:
importance.sort_values(
    by="weight",
    ascending=False
)

                     feature    weight
0                 first_girl  2.335283
13         hair_color_Orange  0.922014
12          hair_color_Green  0.917445
44       setting_High School  0.729357
26              medium_Anime  0.524782
..                       ...       ...
6   has_childhood_connection -0.682773
5           introduced_early -0.716274
17         hair_color_Silver -0.819269
9          hair_color_Blonde -0.843938
1         introduction_order -0.870357

[71 rows x 2 columns]

In [35]:
# biggest loser predictors
importance.sort_values(
    by="weight",
    ascending=True
)

                     feature    weight
1         introduction_order -0.870357
9          hair_color_Blonde -0.843938
17         hair_color_Silver -0.819269
5           introduced_early -0.716274
6   has_childhood_connection -0.682773
..                       ...       ...
26              medium_Anime  0.524782
44       setting_High School  0.729357
12          hair_color_Green  0.917445
13         hair_color_Orange  0.922014
0                 first_girl  2.335283

[71 rows x 2 columns]

In [37]:
y_pred = LOGmodel.predict(X_test)

In [38]:
comparison = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

comparison.head(10)

     Actual  Predicted
287       0          0
329       0          0
323       0          0
145       0          0
55        0          1
93        0          0
340       0          0
82        0          0
365       1          0
148       0          0

In [39]:
accuracy_score(y_test, y_pred)

0.9210526315789473

In [40]:
print(classification_report(
    y_test,
    y_pred
))

              precision    recall  f1-score   support

           0       0.94      0.97      0.96        66
           1       0.75      0.60      0.67        10

    accuracy                           0.92        76
   macro avg       0.85      0.78      0.81        76
weighted avg       0.92      0.92      0.92        76

In [42]:

confusion_matrix(
    y_test,
    y_pred
)

array([[64,  2],
       [ 4,  6]])

In [43]:
importance.sort_values(
    by="weight",
    ascending=False
).head(10)

                        feature    weight
0                    first_girl  2.335283
13            hair_color_Orange  0.922014
12             hair_color_Green  0.917445
44          setting_High School  0.729357
26                 medium_Anime  0.524782
15            hair_color_Purple  0.516595
58  setting_Supernatural School  0.501800
43      setting_Fantasy Kingdom  0.411203
4            high_heroine_count  0.334653
40              setting_College  0.317841

In [44]:
importance.sort_values(
    by="weight",
    ascending=True
).head(10)

                       feature    weight
1           introduction_order -0.870357
9            hair_color_Blonde -0.843938
17           hair_color_Silver -0.819269
5             introduced_early -0.716274
6     has_childhood_connection -0.682773
50     setting_Monster Academy -0.543680
56  setting_Supernatural Drama -0.531659
23  primary_archetype_Onee-san -0.527973
55       setting_Shrine/School -0.519098
11            hair_color_Brown -0.466276

KeyError: 'setting'